kind: pipeline
type: docker
name: build-iot-new

steps:
  - name: test
    image: maven:3-jdk-10
    volumes:
      - /home/docker/maven/m2:/root/.m2
    commands:
      - echo 'testtest'
      - cd  ./simple-pom
      - mvn -U clean install -DskipTests=true -Dmaven.javadoc.skip=true -B
volumes:
  - name: mvncache
    host:
      path: /var/lib/cache/.m2

trigger:
  branch:
    - master
  event:
    - push
