kind: pipeline
type: docker
name: build-iot-new

steps:
  - name: test
    image: maven:latest
    commands:
      - echo 'testtest'
      - cd  ./simple-pom
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
trigger:
  branch:
    - master
  event:
    - push
